apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: rwdnas1/githubactions-aks-demo:0.0.1'  # Dynamic reference to the pushed image
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: customer
