apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nosql-db
  template:
    metadata:
      labels:
        app: nosql-db
    spec:
      containers:
        - name: nosql-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: db-storage
              mountPath: /data/db
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nosql-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: nosql-db
