apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: rwdnas1/githubactions-aks-demo:0.0.1  # Dynamic reference to the pushed image
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: NodePort
  ports:
    - port: 8002       # The port that your application is exposed on
      targetPort: 8002 # The port in your container
      nodePort: 32103  # The NodePort for external access

  selector:
    app: products
