apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: rwdnas1/githubactions-aks-demo:0.0.1  # Dynamic reference to the pushed image
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: NodePort  # LoadBalancer should be set here in the spec level
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: products
