apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: ruwadregistry123.azurecr.io/shopping:latest
          ports:
            - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: shopping
spec:
  ports:
    - port: 8003
      targetPort: 8003
  selector:
    app: shopping
