name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      # Login via Azure CLI
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and Push Docker Images
      - name: 'Build and Push Docker Images'
        run: |
          # Build and push each service image
          docker build ./products -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/products:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/products:latest

          docker build ./shopping -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/shopping:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/shopping:latest

          docker build ./customer -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/customer:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/customer:latest

          docker build ./proxy -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-proxy:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-proxy:latest

      # Set up Kubernetes context
      - name: 'Set up K8s context'
        uses: azure/aks-set-context@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: 'ruwad51'  # Replace with your AKS cluster name
          admin: false

      # Deploy to AKS
      - name: 'Deploy to AKS'
        uses: azure/k8s-deploy@v1
        with:
          manifests: ./manifests/*.yaml  # Path to your Kubernetes manifests
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/products:latest
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/shopping:latest
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/customer:latest
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-proxy:latest
