name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      # Login via Azure CLI
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and Push Docker Images
      - name: 'Build and Push Docker Images'
        run: |
          # Build and push each service image
          docker build ./products -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/products:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/products:${{ github.sha }}

          docker build ./shopping -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/shopping:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/shopping:${{ github.sha }}

          docker build ./customer -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/customer:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/customer:${{ github.sha }}

          docker build ./proxy -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-proxy:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-proxy:${{ github.sha }}

      # Set up Kubernetes context
      - name: 'Set up K8s context'
        uses: azure/aks-set-context@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: 'ruwad51'  # Replace with your AKS cluster name
          admin: false

      # Deploy to AKS using all manifests
      - name: 'Deploy to AKS'
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ./manifests/customer.yml
            ./manifests/mongo-pvc.yml
            ./manifests/nginx-proxy.yml
            ./manifests/nosql-db.yml
            ./manifests/products.yml
            ./manifests/shopping.yml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/products:${{ github.sha }}
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/shopping:${{ github.sha }}
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/customer:${{ github.sha }}
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-proxy:${{ github.sha }}
